name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEV_EC2_PEM }}" > ~/.ssh/deploy_key.pem
          chmod 600 ~/.ssh/deploy_key.pem

      - name: Build the Project
        run: |
          mvn clean install -DskipTests

      - name: Deploy to EC2
        run: |
          # Connect to EC2 and kill the previous Java process if running
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key.pem ubuntu@ec2-18-117-162-62.us-east-2.compute.amazonaws.com "pkill -f java || true"

          # Copy the built jar file to EC2
          scp -i ~/.ssh/deploy_key.pem target/app.jar ubuntu@ec2-18-117-162-62.us-east-2.compute.amazonaws.com:/home/ubuntu/app.jar

          # Restart the application with the correct Spring profile (local)
          ssh -i ~/.ssh/deploy_key.pem ubuntu@ec2-18-117-162-62.us-east-2.compute.amazonaws.com "nohup java -Dspring.profiles.active=local -jar /home/ubuntu/app.jar &"
